import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'core/theme/theme.dart';
import 'core/di/injection_container.dart' as di;
import 'features/auth/presentation/screens/login_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Must run before anything touches Firebase or Google Sign-In.
  await Firebase.initializeApp();
  // If you later run `flutterfire configure`, swap the line above for:
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // and import 'firebase_options.dart' (auto-generated by the CLI).

  await dotenv.load(fileName: '.env');
  await di.init();

  runApp(const ShadowChatApp());
}

class ShadowChatApp extends StatelessWidget {
  const ShadowChatApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Shadow Chat',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.dark,
      home: const LoginScreen(),
    );
  }
}
